name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Text 1
        id: cache-text
        uses: actions/cache@v2
        with:
          path: ./test-1.txt
          key: ${{ runner.os }}-text

      - name: Generate Text 1
        if: steps.cache-text-1.outputs.cache-hit != 'true'
        run: echo "test 1" >> ./test-1.txt

      - name: Use Text 1
        run: |
          cat ./test-1.txt
          
      - name: Cache Text 2
        id: cache-text-2
        uses: actions/cache@v2
        with:
          path: ./test-2.txt
          key: ${{ runner.os }}-text-2

      - name: Generate Text 2
        if: steps.cache-text-2.outputs.cache-hit != 'true'
        run: echo "test 2" >> ./test-2.txt

      - name: Use Text 2
        run: |
          cat ./test-2.txt
